Repository RoinujNosde/Dynmap-SimpleClans, pull requests merged in 2022-06, with the labels that each got.

#13 2.0.0 release
  .github/workflows/maven.yml
  .github/workflows/release-please.yml
  Dynmap-SimpleClans.iml
  dependency-reduced-pom.xml
  org/bukkit/configuration/annotations.xml
  pom.xml
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/DynmapSimpleClans.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/DynmapSimpleClansListener.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/Helper.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/IconStorage.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/Toggles.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/entries/KillEntry.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/entries/PlayerEntry.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/ClanHomes.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/Kills.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/LayerConfig.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/managers/CommandManager.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/managers/PlayerManager.java
  src/main/java/net/sacredlabyrinth/phaed/dynmap/simpleclans/managers/PreferencesManager.java
  src/main/kotlin/net/sacredlabyrinth/phaed/dynmap/simpleclans/DynmapSimpleClansListener.kt
  src/main/kotlin/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/HomesLayer.kt
  src/main/kotlin/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/KillsLayer.kt
  src/main/kotlin/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/LandsLayer.kt
  src/main/kotlin/net/sacredlabyrinth/phaed/dynmap/simpleclans/layers/Layer.kt
  src/main/kotlin/net/sacredlabyrinth/phaed/dynmap/simpleclans/tasks/HideWarringClansTask.kt
  src/main/resources/config.yml
  src/main/resources/plugin.yml
  src/test/net/sacredlabyrinth/phaed/dynmap/simpleclans/HelperTest.java
  src/test/net/sacredlabyrinth/phaed/dynmap/simpleclans/IconStorageTest.java
Labels: enhancement

#18 chore(master): release 2.0.1
  CHANGELOG.md
  dependency-reduced-pom.xml
  pom.xml
Labels: autorelease: pending

#19 chore(master): release 2.0.2-SNAPSHOT
  dependency-reduced-pom.xml
  pom.xml
Labels: autorelease: snapshot
